services:
  app:
    build:
      context: ./scraper
    volumes:
      - ./scraper:/app
  #   depends_on:
  #     - selenium

  # selenium:
  #   image: selenium/standalone-chrome:latest
  #   ports:
  #     - "4444:4444"
  #   shm_size: "2gb"
